stages:
  - build
  - deploy

build:
  image: node:12 
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - /*
  tags:
    - docker

swagger:
  stage: swagger
  dependencies:
    - build
  script:
    - mkdir -p "/var/www/swagger/nh5050/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHORT_SHA"
    - cp docs/swagger.yaml "/var/www/swagger/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHORT_SHA"
    - cp docs/swagger.yaml "/var/www/swagger/$CI_COMMIT_REF_NAME"
  tags:
    - swagger
  
deployToDev:
  stage: deploy
  script:
    - docker build . -t 5050-backend
    - deployBackend
  only:
    - develop
  tags:
    - 5050dev

deployToStaging:
  stage: deploy
  script:
    - cp -R ../NH5050-backend $PROJECT_DIR
    - deployBackend
  tags:
    - 5050stage
  when: manual
